global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'factstore-command'
    static_configs:
      - targets: ['backend-command:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'factstore-query'
    static_configs:
      - targets: ['backend-query:8080']
    metrics_path: '/actuator/prometheus'
