package com.factstore.core.domain

import jakarta.persistence.*
import java.time.Instant
import java.util.UUID

/**
 * Append-only event log entry. Each row is an immutable record of a domain
 * event that was emitted as part of a state transition.
 *
 * The `sequence_number` column is the primary key and is generated by the
 * database as an IDENTITY value (see V33 migration), guaranteeing a
 * monotonically-increasing, gap-free ordering of all events.
 */
@Entity
@Table(name = "domain_events")
class EventLogEntry(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sequence_number")
    var sequenceNumber: Long = 0,

    @Column(name = "event_id", nullable = false, unique = true)
    val eventId: UUID = UUID.randomUUID(),

    @Column(name = "aggregate_id", nullable = false)
    val aggregateId: UUID,

    @Column(name = "aggregate_type", nullable = false, length = 64)
    val aggregateType: String,

    @Column(name = "event_type", nullable = false, length = 128)
    val eventType: String,

    @Column(name = "payload", nullable = false, columnDefinition = "TEXT")
    val payload: String,

    @Column(name = "metadata", columnDefinition = "TEXT")
    val metadata: String? = null,

    @Column(name = "occurred_at", nullable = false)
    val occurredAt: Instant = Instant.now()
)
